name: update list

on:
  schedule:
  - cron: "0 3 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch List
      run: ./blocklist-build.sh 
    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.0.0
      with:
        repo_token: "${{ secrets.RELEASE_TOKEN }}"
        automatic_release_tag: latest
        prerelease: false
        files: blocklist.gz
